import {
  validateWorldExchange,
  type WorldExchange,
} from "@simulation-external/world-schema";

const candidateWorldFixture: WorldExchange = {
  schemaVersion: 1,
  world: {
    id: "world-lyr",
    name: "The Lyran Reach",
    era: "The Quiet Meridian",
    description:
      "A coastal world rebuilding its trade routes after a generation of storms.",
  },
  cities: [
    {
      id: "city-aurora",
      name: "Aurora Quay",
      tags: ["port", "coastal"],
      region: "The Astrel Coast",
      populationSummary:
        "About 42,000 residents; sailors, chartmakers, and fishers form its largest communities.",
      foundedYear: 418,
      locationId: "place-aurora",
      organizationIds: ["org-navigators", "org-aurora-watch"],
      importantPersonIds: ["person-lyra", "person-tomas"],
      description:
        "A sheltered port whose old sea wall is covered in route marks and memorial bells.",
    },
    {
      id: "city-bracken",
      name: "Brackenford",
      region: "The Astrel Coast",
      populationSummary:
        "About 18,000 residents, with many millers and river pilots.",
      foundedYear: 506,
      locationId: "place-bracken",
      organizationIds: ["org-river-wardens"],
      importantPersonIds: ["person-sora", "person-jalen"],
      description:
        "A market town straddling the only reliable bridge over the Astrel River.",
    },
    {
      id: "city-cinder",
      name: "Cinderwatch",
      region: "The Ashen Uplands",
      populationSummary:
        "About 11,000 residents; much of the town works in ceramic kilns and copper shops.",
      foundedYear: 231,
      locationId: "place-cinder",
      organizationIds: ["org-ironmakers"],
      importantPersonIds: ["person-dara", "person-feo"],
      description:
        "A hillside city known for its heat-resistant glass and slate-roofed foundries.",
    },
  ],
  locations: [
    {
      id: "region-astrel",
      name: "Astrel Coast",
      kind: "region",
      description: "The western shore of the Lyran Reach.",
    },
    {
      id: "place-aurora",
      name: "Aurora Quay",
      kind: "city",
      cityId: "city-aurora",
      parentLocationId: "region-astrel",
    },
    {
      id: "place-bracken",
      name: "Brackenford",
      kind: "city",
      cityId: "city-bracken",
      parentLocationId: "region-astrel",
    },
    {
      id: "place-cinder",
      name: "Cinderwatch",
      kind: "city",
      cityId: "city-cinder",
      parentLocationId: "region-astrel",
    },
    {
      id: "harbor-aurora",
      name: "Old Harbor",
      kind: "district",
      cityId: "city-aurora",
      parentLocationId: "place-aurora",
    },
    {
      id: "archive-aurora",
      name: "Tide Archive",
      kind: "building",
      cityId: "city-aurora",
      parentLocationId: "place-aurora",
    },
    {
      id: "observatory-aurora",
      name: "North Lantern Observatory",
      kind: "landmark",
      cityId: "city-aurora",
      parentLocationId: "place-aurora",
    },
    {
      id: "market-bracken",
      name: "Bridge Market",
      kind: "district",
      cityId: "city-bracken",
      parentLocationId: "place-bracken",
    },
    {
      id: "river-gate",
      name: "North River Gate",
      kind: "landmark",
      cityId: "city-bracken",
      parentLocationId: "place-bracken",
    },
    {
      id: "foundry-cinder",
      name: "Copper Hearth Foundry",
      kind: "building",
      cityId: "city-cinder",
      parentLocationId: "place-cinder",
    },
  ],
  people: [
    {
      id: "person-lyra",
      name: "Lyra Venn",
      tags: ["navigator", "chartmaker"],
      age: 34,
      occupation: "navigator",
      residenceId: "city-aurora",
      locationId: "observatory-aurora",
      organizationIds: ["org-navigators"],
      institutionIds: ["inst-tide-archive"],
      factionIds: ["faction-dawn-concord"],
      relationshipIds: ["rel-lyra-tomas", "rel-lyra-miri", "rel-lyra-jalen"],
      biography:
        "Keeps a hand-drawn atlas of safe passages through the storm belt.",
    },
    {
      id: "person-tomas",
      name: "Tomas Rill",
      age: 47,
      occupation: "harbor marshal",
      residenceId: "city-aurora",
      locationId: "harbor-aurora",
      organizationIds: ["org-aurora-watch"],
      factionIds: ["faction-dawn-concord"],
      relationshipIds: ["rel-lyra-tomas", "rel-tomas-mira", "rel-tomas-oren"],
    },
    {
      id: "person-mira",
      name: "Mira Sol",
      age: 29,
      occupation: "physician",
      residenceId: "city-aurora",
      locationId: "harbor-aurora",
      institutionIds: ["inst-lantern-clinic"],
      relationshipIds: ["rel-tomas-mira"],
    },
    {
      id: "person-jalen",
      name: "Jalen Orr",
      age: 25,
      occupation: "river pilot",
      residenceId: "city-bracken",
      locationId: "river-gate",
      organizationIds: ["org-river-wardens", "org-navigators"],
      institutionIds: ["inst-bracken-college"],
      factionIds: ["faction-free-harbor"],
      relationshipIds: ["rel-jalen-sora", "rel-jalen-selene", "rel-lyra-jalen"],
    },
    {
      id: "person-sora",
      name: "Sora Pell",
      age: 39,
      occupation: "bridge keeper",
      residenceId: "city-bracken",
      locationId: "market-bracken",
      organizationIds: ["org-river-wardens"],
      factionIds: ["faction-free-harbor"],
      relationshipIds: ["rel-jalen-sora", "rel-sora-eli", "rel-sora-oran"],
    },
    {
      id: "person-miri",
      name: "Miri Fen",
      age: 58,
      occupation: "archivist",
      residenceId: "city-aurora",
      locationId: "archive-aurora",
      institutionIds: ["inst-tide-archive"],
      factionIds: ["faction-dawn-concord"],
      relationshipIds: ["rel-lyra-miri", "rel-miri-oren"],
    },
    {
      id: "person-oren",
      name: "Oren Vale",
      age: 42,
      occupation: "shipwright",
      residenceId: "city-aurora",
      locationId: "harbor-aurora",
      organizationIds: ["org-aurora-watch"],
      relationshipIds: ["rel-tomas-oren", "rel-miri-oren"],
    },
    {
      id: "person-eli",
      name: "Eli Moss",
      age: 31,
      occupation: "ferryman",
      residenceId: "city-bracken",
      locationId: "river-gate",
      organizationIds: ["org-river-wardens"],
      factionIds: ["faction-free-harbor"],
      relationshipIds: ["rel-sora-eli"],
    },
    {
      id: "person-dara",
      name: "Dara Kest",
      age: 51,
      occupation: "master glassmaker",
      residenceId: "city-cinder",
      locationId: "foundry-cinder",
      organizationIds: ["org-ironmakers"],
      institutionIds: ["inst-cinder-infirmary"],
      relationshipIds: ["rel-dara-feo"],
    },
    {
      id: "person-feo",
      name: "Feo Ardin",
      age: 22,
      occupation: "apprentice glassmaker",
      residenceId: "city-cinder",
      locationId: "foundry-cinder",
      organizationIds: ["org-ironmakers"],
      relationshipIds: ["rel-dara-feo", "rel-feo-oran"],
    },
    {
      id: "person-selene",
      name: "Selene Ar",
      age: 36,
      occupation: "cartographer",
      residenceId: "city-bracken",
      locationId: "market-bracken",
      organizationIds: ["org-navigators"],
      institutionIds: ["inst-bracken-college"],
      relationshipIds: ["rel-jalen-selene"],
    },
    {
      id: "person-oran",
      name: "Oran Vey",
      age: 63,
      occupation: "council speaker",
      residenceId: "city-cinder",
      locationId: "place-cinder",
      factionIds: ["faction-free-harbor"],
      relationshipIds: ["rel-feo-oran", "rel-sora-oran"],
    },
  ],
  organizations: [
    {
      id: "org-navigators",
      name: "Meridian Navigators' Guild",
      type: "guild",
      cityId: "city-aurora",
      locationId: "observatory-aurora",
      memberIds: ["person-lyra", "person-jalen", "person-selene"],
      factionIds: ["faction-dawn-concord"],
      description:
        "Shares route charts and trains pilots to read the shifting stars.",
    },
    {
      id: "org-aurora-watch",
      name: "Aurora Harbor Watch",
      type: "civic guard",
      cityId: "city-aurora",
      locationId: "harbor-aurora",
      memberIds: ["person-tomas", "person-oren"],
      factionIds: ["faction-dawn-concord"],
    },
    {
      id: "org-river-wardens",
      name: "Astrel River Wardens",
      type: "stewardship order",
      cityId: "city-bracken",
      locationId: "river-gate",
      memberIds: ["person-jalen", "person-sora", "person-eli"],
      factionIds: ["faction-free-harbor"],
    },
    {
      id: "org-ironmakers",
      name: "Cinder Ironmakers' Cooperative",
      type: "trade cooperative",
      cityId: "city-cinder",
      locationId: "foundry-cinder",
      memberIds: ["person-dara", "person-feo"],
    },
  ],
  institutions: [
    {
      id: "inst-tide-archive",
      name: "Tide Archive",
      type: "public archive",
      cityId: "city-aurora",
      locationId: "archive-aurora",
      memberIds: ["person-lyra", "person-miri"],
    },
    {
      id: "inst-bracken-college",
      name: "Bracken College of Measures",
      type: "school",
      cityId: "city-bracken",
      locationId: "market-bracken",
      memberIds: ["person-jalen", "person-selene"],
    },
    {
      id: "inst-lantern-clinic",
      name: "Lantern Clinic",
      type: "clinic",
      cityId: "city-aurora",
      locationId: "harbor-aurora",
      memberIds: ["person-mira"],
    },
    {
      id: "inst-cinder-infirmary",
      name: "Cinder Infirmary",
      type: "infirmary",
      cityId: "city-cinder",
      locationId: "foundry-cinder",
      memberIds: ["person-dara"],
    },
  ],
  factions: [
    {
      id: "faction-dawn-concord",
      name: "Dawn Concord",
      ideology: "Shared stewardship of coastal routes and civic records.",
      memberIds: ["person-lyra", "person-tomas", "person-miri"],
      cityIds: ["city-aurora", "city-bracken"],
      organizationIds: ["org-navigators", "org-aurora-watch"],
      description:
        "A loose alliance that coordinates harbor law and the public chart archive.",
    },
    {
      id: "faction-free-harbor",
      name: "Free Harbor League",
      ideology: "Local control of river crossings and fair access to trade.",
      memberIds: ["person-jalen", "person-sora", "person-eli", "person-oran"],
      cityIds: ["city-bracken", "city-cinder"],
      organizationIds: ["org-river-wardens"],
      description:
        "A coalition of river communities wary of distant harbor taxes.",
    },
  ],
  items: [
    {
      id: "item-stormglass-sextant",
      name: "Stormglass Sextant",
      type: "navigation instrument",
      ownerId: "person-lyra",
      locationId: "observatory-aurora",
      description:
        "A brass instrument with a lens made from glass recovered after the Great Gale.",
    },
    {
      id: "item-river-charter",
      name: "North River Charter",
      type: "civic document",
      ownerId: "person-miri",
      locationId: "archive-aurora",
    },
    {
      id: "item-cinder-seed-vault",
      name: "Ashseed Vault",
      type: "seed collection",
      ownerId: "person-dara",
      locationId: "foundry-cinder",
      description:
        "A heatproof case holding the last seed stock from the upland orchards.",
    },
  ],
  historicalEvents: [
    {
      id: "event-broken-bell",
      title: "The Broken Bell Truce",
      year: 612,
      occurredAt: "0612-09-18",
      description:
        "Three cities agreed to suspend tolls after the old harbor bell cracked during a storm surge.",
      participantIds: [
        "person-lyra",
        "person-tomas",
        "person-sora",
        "person-miri",
      ],
      locationIds: ["harbor-aurora", "river-gate"],
      relatedEntityIds: [
        "item-river-charter",
        "faction-dawn-concord",
        "faction-free-harbor",
      ],
    },
    {
      id: "event-north-chart",
      title: "The North Passage Charting",
      year: 619,
      occurredAt: "0619-04-03",
      description:
        "A joint expedition marked a safer route through the northern shoals.",
      participantIds: ["person-lyra", "person-jalen", "person-selene"],
      locationIds: ["observatory-aurora", "market-bracken"],
      relatedEntityIds: [
        "item-stormglass-sextant",
        "org-navigators",
        "event-broken-bell",
      ],
    },
    {
      id: "event-ash-orchard",
      title: "Restoration of the Ash Orchard",
      year: 625,
      occurredAt: "0625-06-10",
      description:
        "Cinderwatch began replanting the upland orchard using seeds preserved through several hard winters.",
      participantIds: ["person-dara", "person-feo", "person-oran"],
      locationIds: ["foundry-cinder", "place-cinder"],
      relatedEntityIds: ["item-cinder-seed-vault", "inst-cinder-infirmary"],
    },
  ],
  relationships: [
    {
      id: "rel-lyra-tomas",
      sourceId: "person-lyra",
      targetId: "person-tomas",
      type: "trusted colleague",
      sinceYear: 608,
    },
    {
      id: "rel-lyra-miri",
      sourceId: "person-lyra",
      targetId: "person-miri",
      type: "research partners",
      sinceYear: 610,
    },
    {
      id: "rel-tomas-mira",
      sourceId: "person-tomas",
      targetId: "person-mira",
      type: "siblings",
    },
    {
      id: "rel-tomas-oren",
      sourceId: "person-tomas",
      targetId: "person-oren",
      type: "former shipmates",
    },
    {
      id: "rel-jalen-sora",
      sourceId: "person-jalen",
      targetId: "person-sora",
      type: "mentor and apprentice",
      sinceYear: 616,
    },
    {
      id: "rel-jalen-selene",
      sourceId: "person-jalen",
      targetId: "person-selene",
      type: "charting partners",
    },
    {
      id: "rel-sora-eli",
      sourceId: "person-sora",
      targetId: "person-eli",
      type: "co-wardens",
    },
    {
      id: "rel-miri-oren",
      sourceId: "person-miri",
      targetId: "person-oren",
      type: "neighbors",
    },
    {
      id: "rel-dara-feo",
      sourceId: "person-dara",
      targetId: "person-feo",
      type: "master and apprentice",
    },
    {
      id: "rel-feo-oran",
      sourceId: "person-feo",
      targetId: "person-oran",
      type: "civic sponsor",
    },
    {
      id: "rel-lyra-jalen",
      sourceId: "person-lyra",
      targetId: "person-jalen",
      type: "guild colleagues",
    },
    {
      id: "rel-sora-oran",
      sourceId: "person-sora",
      targetId: "person-oran",
      type: "political allies",
    },
  ],
};

const validation = validateWorldExchange(candidateWorldFixture);
if (!validation.valid) {
  throw new Error(
    `Invalid built-in world fixture: ${validation.issues.map((issue) => `${issue.path} (${issue.code})`).join(", ")}`,
  );
}

/** The ready-to-use fixture, validated by @simulation-external/world-schema. */
export const worldFixture = validation.value;

/** Alias emphasizing that this value passed runtime validation. */
export const validatedWorldFixture = worldFixture;
